use_frameworks!

target 'CircularWordsCloud_Example' do
  pod 'CircularWordsCloud', :path => '../'

  target 'CircularWordsCloud_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
